version: "3"

networks:
  service-network:
    driver: bridge

services:
  mongoDataBase:
    container_name: MSA-Mongo
    hostname: mainMongo
    image: mongo
    networks:
      - service-network
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodData:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: doukhee
    logging:
      options:
        max-file: "3"
        max-size: "10MB"